import { Biriyani, GajarkaHalwa, Jalebi, MasalaDosa, ButterChicken, Samosas, Naan, TandooriChicken, PalakPaneer, ChanaMasala, DalMakhni, Idli, Vada, Dhokla, Uttapam, Chaat, Rasmalai, GulabJamun, Laddoo, Barfi, Kheer, Payas, Falooda } from "../assets/Food-Images"

export const MenuList = [
    {
        "id": 1,
        "name": "Biriyani",
        "description": "A rice dish cooked with spices, meat, vegetables, and yogurt.",
        "image": Biriyani,
        "price" : 200,
        "category": "Non-veg",
    },
    {
        "id": 2,
        "name": "Masala dosa",
        "description": "A thin crepe made from fermented rice and lentil batter.",
        "image": MasalaDosa,
        "price" : 70,
        "category": "Veg",
    },
    {
        "id": 3,
        "name": "Butter chicken",
        "description": "A dish of chicken cooked in a creamy tomato sauce.",
        "price" : 120,
        "image": ButterChicken,
        
        "category": "Non-veg",
    },
    {
        "id": 4,
        "name": "Samosas",
        "description": "Deep-fried pastries filled with a savory potato and pea mixture.",
        "image": Samosas,
        "price" : 10,
        "category": "Veg",
    },
    {
        "id": 5,
        "name": "Naan",
        "description": "A leavened flatbread cooked in a tandoor oven.",
        "image": Naan,
        "price" : 20,
        "category": "Veg",
    },
    {
        "id": 6,
        "name": "Tandoori chicken",
        "description": "Chicken marinated in yogurt and spices and cooked in a tandoor oven.",
        "image": TandooriChicken,
        "price" : 150,
        "category": "Non-veg",
    },
    {
        "id": 7,
        "name": "Palak paneer",
        "description": "A dish of paneer cheese cooked in a spinach sauce.",
        "image": PalakPaneer,
        "price" : 120,
        "category": "Veg",
    },
    {
        "id": 8,
        "name": "Chana masala",
        "description": "A dish of chickpeas cooked in a tomato and onion sauce.",
        "image": ChanaMasala,
        "price" : 80,
        "category": "Veg",
    },
    {
        "id": 9,
        "name": "Dal makhani",
        "description": "A lentil dish cooked in a creamy tomato sauce.",
        "image": DalMakhni,
        "price" : 100,
        "category": "Veg",
    },
    {
        "id": 10,
        "name": "Idli",
        "description": "Steamed cakes made from fermented rice and lentil batter.",
        "image": Idli,
        "price" : 15,
        "category": "Veg",
    },
    {
        "id": 11,
        "name": "Vada",
        "description": "Deep-fried savory donuts made from lentil batter.",
        "image": Vada,
        "price" : 10,
        "category": "Veg",
    },
    {
        "id": 12,
        "name": "Dhokla",
        "description": "Steamed cakes made from fermented chickpea batter.",
        "image": Dhokla,
        "price" : 20,
        "category": "Veg",
    },
    {
        "id": 13,
        "name": "Uttapam",
        "description": "A thick pancake made from fermented rice and lentil batter.",
        "image": Uttapam,
        "price" : 60,
        "category": "Veg",
    },
    {
        "id": 14,
        "name": "Chaat",
        "description": "A savory snack made with a variety of ingredients, such as potatoes, chickpeas.",
        "image": Chaat,
        "price" : 30,
        "category": "Veg",
    },
    {
        "id": 15,
        "name": "Rasmalai",
        "description": "Balls of paneer cheese soaked in a sweet milk syrup.",
        "image": Rasmalai,
        "price" : 20,
        "category": "Veg",
    },
    {
        "id": 16,
        "name": "Gulab jamun",
        "description": "Milk solids deep-fried in syrup and then soaked in sugar syrup.",
        "image": GulabJamun,
        "price" : 10,
        "category": "Veg",
    },
    {
        "id": 17,
        "name": "Jalebi",
        "description": "Deep-fried batter spirals soaked in sugar syrup.",
        "image": Jalebi,
        "price" : "12 / 100 g",
        "category": "Veg",
    },
    {
        "id": 18,
        "name": "Ladoo",
        "description": "Sweet balls made with various ingredients, such as gram flour, sugar, and nuts.",
        "image": Laddoo,
        "price" : 7,
        "category": "Veg",
    },
    {
        "id": 19,
        "name": "Barfi",
        "description": "A dense, fudge-like sweet made with milk, sugar, and nuts.",
        "image": Barfi,
        "price" : 10,
        "category": "Veg",
    },
    {
        "id": 20,
        "name": "Gajar ka halwa",
        "description": " A carrot pudding dessert made with carrots, milk, sugar, and nuts.",
        "image": GajarkaHalwa,
        "price" : 60,
        "category": "Veg",
    },
    {
        "id": 21,
        "name": "Kheer",
        "description": "A rice pudding dessert made with milk, sugar, and rice.",
        "image": Kheer,
        "price" : 40,
        "category": "Veg",
    },
    {
        "id": 22,
        "name": "Payasam",
        "description": " A sweet milk porridge made with milk, sugar, and rice or vermicelli.",
        "image": Payas,
        "price" : 60,
        "category": "Veg",
    },
    {
        "id": 23,
        "name": "Falooda",
        "description": "A cold dessert made with milk, sugar, ice cream, vermicelli, and nuts.",
        "image": Falooda,
        "price" : 60,
        "category": "Veg",
    },
]